services:

  db:
    image: postgres:15

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: camaccess

    ports:
      - "5432:5432"

  backend:
    build: ./backend

    ports:
      - "3000:3000"

    depends_on:
      - db

  frontend:
    build: ./frontend

    ports:
      - "3001:3000"

    depends_on:
      - backend
